const sectionlist = {
    "HOME": {"kr": "전체", "url": "/"},
    "NEWS" : {"kr": "뉴스", "url": "/NEWS"},
    "cover" : {"kr": "표지이야기", "url": "/arti/SERIES"},
    "cover_general" : {"kr": "표지이야기일반", "url": "/arti/SERIES"},
    "special" : {"kr": "특집", "url": "/arti/SERIES"},
    "special_general" : {"kr": "특집일반", "url": "/arti/SERIES"},
    "politics" : {"kr": "정치", "url": "/arti/politics"},
    "politics_general" : {"kr": "정치일반", "url": "/arti/politics/politics_general"},
    "economy" : {"kr": "경제", "url": "/arti/economy"},
    "economy_general" : {"kr": "경제일반"},
    "society" : {"kr": "사회", "url": "/arti/society"},
    "society_general" : {"kr": "사회일반"},
    "environment" : {"kr": "환경", "url": "/arti/environment"},
    "world" : {"kr": "세계", "url": "/arti/world"},
    "world_general" : {"kr": "세계일반"},
    "photo" : {"kr": "멀티미디어", "url": "/arti/photo"},
    "oneshot" : {"kr": "원샷"},
    "story" : {"kr": "포토스토리"},
    "cartoon" : {"kr": "카툰"},
    "people" : {"kr": "당신"},
    "culture" : {"kr": "문화", "url": "/arti/culture"},
    "culture_general" : {"kr": "문화일반"},
    "reader" : {"kr": "독자", "url": "/arti/reader"},
    "together" : {"kr": "독자와함께", "url": "/arti/reader/together"},
    "reader_edit" : {"kr": "독자편집위원회"},
    "reader_campaign" : {"kr": "캠페인"},
    "HERI" : {"kr": "HERI"},
    "H_special" : {"kr": "H_특집"},
    "H_theme" : {"kr": "H_기획"},
    "H_general" : {"kr": "H_일반"},
    "COLUMN" : {"kr": "칼럼", "url": "/arti/COLUMN"},
    "SERIES" : {"kr": "기획연재", "url": "/arti/SERIES"},
    "HO" : {"kr": "차례보기"}
}

export default sectionlist;
